version: "3"
services:
  app:
    container_name: tinycoin
    restart: always
    build: .
    ports:
      - "4040:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
